version: '3.8'

services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=host.docker.internal
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=adaca
      - DATABASE_PORT=5438
      - PORT=3000
    volumes:
      - ./src:/app/src
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - '5438:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: adaca
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
